### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by anitoad** [moidu21/minerplus#12]
It's crashing after today's update, could you check it?
Early Access - v0.5.1.3 - Build 174506
edit:more specifically, it's when I'm trying to place a belt

**Comment by moidu21** [comment]
can't reproduce the crash but i made some change in belt hope that fix it , also moved to latest sml that could help

tell me if it's not working and if not please send the crash log thanks

**Comment by anitoad** [comment]
It seems there is a conflict with Smart! mod, it's working without it.

**Comment by moidu21** [comment]
yep smart mod need to update 
thanks
