### ISSUE TITLE
question about balance

### ISSUE THREAD

**Issue by demongo1154** [moidu21/minerplus#14]
when will the BAM unlocks be moved to the final tiers to balance it with the base game, im not complaining about getting mega high tier belt so early and cheaply but  do we ever intend to move it to late game were it belongs?

**Comment by moidu21** [comment]
i plain to re-do all millestones for the release but before that i want to finish adding content to the mod to make a better balance with the base game, originally this mod only get a miner and 3 belt/lift and it growth over time and for now i'm not thinking for balance or unlock but after for sure

**Comment by moidu21** [comment]
mod will get a balance soon you will need to unlock a shematics at tier8 to start unlocking the other at tier 2 then tier 4 ......
