### ISSUE TITLE
Refinery Recipes

### ISSUE THREAD

**Issue by Ramokthan** [moidu21/minerplus#15]
Can you add all recipes which the default refinery has ?

I dont even mind if it only uses one pipe.

Issue is that the refinery in this state is fairly useless to me since i neither can make use of alternative recipes, eg diluted fuel, nor my other mod (Packing Expansion), which works well with other modded refineries since they pick up that mods recipes automatically somehow.

Would make this mod 50 times more awesome.
:-)

**Comment by moidu21** [comment]
the alternative recipe are planned i will add it soon and make a better way to unlock it after that

i may make a mk2 refinery with just a productivity boost and one pipe to handle correctly the "normal/alternative" recipe,  just need some time

**Comment by moidu21** [comment]
added a refinery mk2 with a productivity boost (X4) for the next update i'm working on
