### ISSUE TITLE
Lead Missing from Scanner if Updating from Older Version With Milestones Unlocked

### ISSUE THREAD

**Issue by mikeloeven** [moidu21/minerplus#16]
Mod needs a update check added to ensure Lead is added to the mineral scanner if the user is loading a save from an older version of the mod where milestones have already been unlocked. I was unable to find a workaround for this issue other than manually resetting the research in a save editor.

**Comment by moidu21** [comment]
good to know will try to make something about that but normally you now can unlockit at tier 8 while it's a new millestone it should be there but i will add a new millestone at tier 0 or 1 to fix that just in case thx for the info

**Comment by moidu21** [comment]
just push an update to solve this with a new millestone thx
