### ISSUE TITLE
screws 

### ISSUE THREAD

**Issue by apzo1985** [moidu21/minerplus#17]
Hey
in mod FBAM, the screws work normally \ move along the tape
when crafting 52k screws and tape at 12k speed
there is a shortage when consuming 3750.
straight line

**Comment by apzo1985** [comment]
the problem lies in the standard delimiters....
apparently they can not work at such speeds

**Comment by moidu21** [comment]
sorry i don't see you here i have made a tiny fix for that normally no more shortage let me konw if that solve this pb
