### ISSUE TITLE
Splitter slowing transfer rate

### ISSUE THREAD

**Issue by LimeSucker** [moidu21/minerplus#19]
The title pretty much sums it all : 

I'm using the 6000 items / minute belt (Mk 8) to feed a line of machine that require 3000 items / minutes in total
However, when I place a splitter to feed, the flow rate slows down in such manner that not all my machines are able to process the items (so flowrate is inferior to 3000 items / minute)

**Comment by Abbaddon911** [comment]
Pretty much everything that "intercepts" the conveyor belts and isn't a machine using the items delivered will limit the speed of the belts.
Doing some tests with the mod "Underground Belts" I found that the limit is somewhere around 1800-2250 items per minute, a bit depending on how much is doing on in your world.
The mergers/splitters provided by BAM (with the inventory) seem to perform slightly better, but I could be wrong on that.

I believe that this behavior is a limitation of either the engine or how the function was programmed.
On other sites, I've also read that even the 780 belt can have some item loss of around 1% in a very full and very late game world. So I kinda doubt that the dev of BAM can really do something this.

**Comment by moidu21** [comment]
i can't do anything for the splitter it's a know issue for a long time for satisfactory, my splitter from bam perform better but it's not perfect but unfortunatly that the best i can do

**Comment by Diantane** [comment]
Instead of using a splitter, try using a small storage. I use a mod called, "Special Containers" that has multiple containers with different numbers of in/outs. I started using them this way to eliminate the same problem you had using splitters. They even have a storage that is the same size of the splitter with 16 spaces inside and two inputs, two outputs.
