### ISSUE TITLE
Mk 4 oil extractor needs one more output 

### ISSUE THREAD

**Issue by Thisdude00** [moidu21/minerplus#2]
First of all, thank you for this amazing mod I appreciate your work.
Suggestion 
Mk4 oil pump on Pure node and with 250% overclock can have 2400m^3/ min oil so with 3 output and mk2 pipe you can only get up to 1800m^3/min oil but if you can add another output we are able to utilize full 2400m^3/min output through our production.
Thank you

**Comment by moidu21** [comment]
thanks for your report

i will add it as soon as possible :)

**Comment by moidu21** [comment]
added in 2.0.8
