### ISSUE TITLE
game crash when building the lift by B.A.M.

### ISSUE THREAD

**Issue by Moonlegis** [moidu21/minerplus#21]
game got crashed when building the lift,no matter MK.8 or MK.10,they will cause the multiplayer games crash in a moment

**Comment by Diantane** [comment]
I reported this on their Discord page a month ago. It was right after their last update. Continued using their mod. Just don't use the lifts (a pain).

**Comment by Diantane** [comment]
Thanks for fixing/deleting the problem. A game file that I spent so much time building is playable again!
