### ISSUE TITLE
Screw Maker out of control

### ISSUE THREAD

**Issue by Diantane** [moidu21/minerplus#22]
Once the Screw Maker fills a container, it just keeps on making screws and robbing resources. It doesn't know when to stop.

**Comment by moidu21** [comment]
are you on u5 or u6, i fixed it on u6 by making it on pause when one of his slot is full but i do not deploy this fix on u5

**Comment by moidu21** [comment]
it's now deploy

**Comment by Diantane** [comment]
Thanks for the fix. Confirmed to be working correctly now!
