### ISSUE TITLE
Wind Turbine Mk 2 output severely reduced 

### ISSUE THREAD

**Issue by Diantane** [moidu21/minerplus#24]
The info says that the output is 350 to 400 MW. Had to link five of them together at mountain top height and at least nine tiles apart to get 400 MW. One only produces 70 to 90 MW depending on the wind. They used to put out 350 to 400 MW about a year ago, but I just recently discovered this site to report issues for my favorite mod.

**Comment by moidu21** [comment]
i just test it and yeah it produce 50 to 100 MW when not linked to anything but it have a max capacity to 350 to 400 MW 
as a side not it's not height or wind related i simulate the wind by changing production every 5 seconds 
please verify if one can produce power for a set of 300 MW linked machines it should work if it's not the case there is probably a mod intearction that causing that

**Comment by moidu21** [comment]
if you have discord you can add me as friend moidu21#3153 i'm more present on discord, i don't always check my github issue tracker

**Comment by Diantane** [comment]
As a single they use to provide 350 to 400 MW. What are you saying? That I would have to connect let's say 5 together to get 350 to 400??

**Comment by moidu21** [comment]
one produce 50 to 100 but have a max capacity at 350 400 (works like a biomass burner produce only if needed) 
normally one could provide 350 to 400 MW on my save the turbine mk2 do it

**Comment by Diantane** [comment]
I see the 350 to 400 MW max capacity, but the most I can get out of it is about 90 MW.

Built the Wind Turbine Mk. 2 in the middle of nowhere. Hooked it to a Power Pole Mk. 2. Then ran four separate wires each to a Power Storage Mk8. The production is only about 90 MW. The charge rate to each storage is 20 to 24 MW each (if I add more power storages this charge amount drops). What good is a 350 to 400 MW max capacity if you can never use it?

**Comment by moidu21** [comment]
ah ok it's confirmed the power storage do not trigger the max capacity (vanilla or mk8) it's look like a bug with it i will see if i can make something

**Comment by moidu21** [comment]
i confirm it's a vanilla bug if you link a biomass burner to a power storage (vanilla) it won't charge i will see if i can make a tweak on the power storage mk8 to accept the max capacity but i'm not sure if i can do that

**Comment by moidu21** [comment]
so i change the way the turbine mk2 produce power the turbine now always produce 350 MW and have a max capacity at 400 because i can't change the way the power storage trigger the max capacity energy
