### ISSUE TITLE
Refinery Mk8 Heavy Oil Residue/Polymer Resin Recipe Bugged: Too Much Polymer Resin

### ISSUE THREAD

**Issue by GrgDev** [moidu21/minerplus#29]
I'll have to update this in a few hours when I am back at home to check the exact version I am using, but it's the normal (non-easy mode) version that is installed by SMM automatically when using the latest public Satisfactory version on the experimental branch. (Should be the same as Early Access branch at time of this writing but detailing here just in case.)

I was playing with B&M last night when I tried to set up a factory using Refinery Mk8's and trying to set them to their equivalent of the alt Heavy Oil Residue recipe.
https://satisfactory.fandom.com/wiki/Refinery?so=search#Recipes
I was under the impression that a Refinery Mk8 should have recipes that are the equivalent of 10 normal Refineries. I tried looking for the Heavy Oil Residue alt recipe to set the Refinery Mk8's to but instead found two different Polymer Resin recipes. 

One of them had an output of Heavy Oil Residue that was correct for the expected Heavy Oil Residue alt recipe but the Polymer Resin output at a normal 100% clock speed is 48000 per minute, much higher than what the recipe is supposed to output and twice as much as the fastest Mk11 belt can even handle. I assume this is a bug and the polymer output resin is supposed to be a lot less. The amount I had to underclock the refineries to get this to work made it eventually easier to just use a few Refinery Mk2's in place of a Refinery Mk8.

PS:
I also tried an experiment where I tried underclocking the Refinery Mk8's to 50% to output 24000 polymer resin per minute instead and using Mk11 belts to dump the polymer resin into an awesome sink. However, in my setup, the polymer resin goes through a vanilla smart splitter and an item transporter from the Storage Transporter mod. (https://ficsit.app/mod/StorageTeleporter) Even though this should result in smooth balanced ratios and transport, the polymer resin seems to continue to get backed up in the Refinery Mk8 and going periodically idle when it hits the max stack size in the output slot buffer. Due to the involvement of the Storage Transporter mod and not testing a direct to sink belt with this experiment, I would not mind considering this behavior out of scope for this issue. Including just in case it is related.

**Comment by moidu21** [comment]
i verify and redo all recipe that as polymer resin in it, it should be ok now
