### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by FallenXuqs** [moidu21/minerplus#3]
Love the mod, but i have some suggestions. Hope u like it.
First, i think u should add a different appearence to conveyors, maybe mk8=mk3(vanilla), mk9=mk4(vanilla) and mk10=mk5(vanilla). 
A less important thing, why dont be mk6,7 and 8 instead of mk8,9,10. I didnt undestand lol. Wheres mk6 and 7 ?

**Comment by moidu21** [comment]
it's in todo list ;) (i would to create my own but i'm really bad at modelling, i may switch for your option)

for the second i start at 8 because why not (primary done to not have 2 building with the same name when you have mk++)
i also need to rename the miner to 8 instead of 4 always forgot :)
