### ISSUE TITLE
Feature: Adding the original recipes

### ISSUE THREAD

**Issue by P4R4NORM4L** [moidu21/minerplus#7]
Why do you limit the recipes that can be created in lets say for example the refinery? or all the other factory buildings in this case?

**Comment by P4R4NORM4L** [comment]
Also, why did you not put any other buildings like the assembler for instance?

**Comment by moidu21** [comment]
dur to the number of pipe i add on it i need to remake all recipe one by one with the correct ratio it's planned but i need time like adding other factory building 

for now i wait for update 5 to make a new update will i already switch my dev environnement

**Comment by P4R4NORM4L** [comment]
Oh ok you can't just speed up the regular recipes?

**Comment by moidu21** [comment]
i can but only if the refinery have one pipe input/output to get the regular recipe 
after that speeding it it's not good due to pipe limitation 600m3/min

**Comment by P4R4NORM4L** [comment]
I see

**Comment by moidu21** [comment]
but i will add it one by one just be patient ;)

**Comment by P4R4NORM4L** [comment]
ok no prob was just wondering why there was a constructor but no assembler and the other machines

**Comment by moidu21** [comment]
time time :)

**Comment by P4R4NORM4L** [comment]
:)

**Comment by moidu21** [comment]
Added all recipe exept altenernate one for now also 
added assembler and manufacturer

**Comment by P4R4NORM4L** [comment]
This is great news!

**Comment by moidu21** [comment]
but i will added in update 5

**Comment by P4R4NORM4L** [comment]
Oh ok when the official update 5 will release, only then will you add them. Sounds good to me.

**Comment by moidu21** [comment]
yep before you cannot launch it without SML and i need to fix belt not working

**Comment by P4R4NORM4L** [comment]
oh ok cool! French ?

**Comment by moidu21** [comment]
oui

**Comment by P4R4NORM4L** [comment]
Parfait merci !

**Comment by moidu21** [comment]
vous me direz si j'ai oublier des recettes le mod est a jour pour l'update 5
excepter les alternatives je pense ne pas en avoir oublier  
j'ai retirer la dépendance a pipe emulation si vous ne voulez pas perdre vos liquid pensez bien a le reprendre dans votre liste de mod

**Comment by P4R4NORM4L** [comment]
Parfait merci !
